[package]
name = "rust-age-testing"
version = "0.1.0"
edition = "2024"

[dependencies]
getrandom = { version="0.3.2",features = ["wasm_js"] }

[dependencies.age]
version = "0.11.1"
features = ["armor"]
getrandom = { features = ["wasm_js"] }

